### ISSUE TITLE
Enhancement: Proxied Response Class

### ISSUE THREAD

**Issue by trisongz** [starlite-api/starlite#772] opened 2022-11-08 17:00 UTC
**What's the feature you'd like to ask for.**

I am using `starlite` as the api framework for microservices within a K8 cluster. I am attempting to build a proxy gateway that handles some conditional logic checks before forwarding and returning the request / response from the downstream api, including `headers` and `cookies` that may have been set by the downstream api.

However, returning the response directly through the `Response` object returns serialization errors, even when using custom serialization unless directly returning the `resp.json()`

It would be more efficient if the returned response can simply be `resp.content` to prevent unnecessary encoding/decoding of the content if the intent is to just be passed through. Is there a more efficient / effective way of accomplishing this?

---

```python
class BaseController(Controller):
    ...

    @get(path = "/healthz/{model_name:str}")
    async def model_healthcheck(
        self,
        model_name: str,
        headers: Optional[Headers] = None,
        cookies: Optional[Dict[str, Any]] = None,
    ) -> HealthCheckResponse:
        """
        Performs a Healthcheck on a model server
        """
        resp = await GatewayEndpoint.forward(
            path = f"{self.path}/",
            model = model_name,
            method = "GET",
            headers = headers,
            cookies = cookies,
        )
        return resp.json()
        # This doesn't work
        # return Response(
        #     content = resp.content, # content = resp.json() also does not work.
        #     media_type = MediaType.JSON,
        #     status_code = resp.status_code,
        #     headers = resp.headers,
        # )

```

**Comment by Goldziher** [comment] 2022-11-08 17:13
Can you show me what is `HealthCheckResponse`?

**Comment by trisongz** [comment] 2022-11-08 17:55
Sure, it's a simple BaseModel. It also applies for `-> Response` types as well.


```python
class HealthCheckResponse(BaseModel):
    status: str

    class Config:
        schema_extra = {
            "example": {
                "status": "alive"
            }
        }
```

**Comment by Goldziher** [comment] 2022-11-08 18:19
So you have two way to handle this:

```python
class BaseController(Controller):
    ...

    @get(path = "/healthz/{model_name:str}")
    async def model_healthcheck(
        self,
        model_name: str,
        headers: Optional[Headers] = None,
        cookies: Optional[Dict[str, Any]] = None,
    ) -> HealthCheckResponse:
        """
        Performs a Healthcheck on a model server
        """
        return await GatewayEndpoint.forward(
            path = f"{self.path}/",
            model = model_name,
            method = "GET",
            headers = headers,
            cookies = cookies,
        )
```

This should work out of the box - Starlite will transform the value into a response properly.

Or if you want to return an explicit response:

```python
from starlite import Response

class BaseController(Controller):
    ...

    @get(path = "/healthz/{model_name:str}")
    async def model_healthcheck(
        self,
        model_name: str,
        headers: Optional[Headers] = None,
        cookies: Optional[Dict[str, Any]] = None,
    ) -> Response[HealthCheckResponse]:
        """
        Performs a Healthcheck on a model server
        """
        resp = await GatewayEndpoint.forward(
            path = f"{self.path}/",
            model = model_name,
            method = "GET",
            headers = headers,
            cookies = cookies,
        )
        return Response(content=resp)
```

**Comment by trisongz** [comment] 2022-11-08 21:32
> btw, both headers and cookies are not optional - that is, they will not be none, although they may be empty

Good to note, thanks!

I tried both methods as you mentioned above, but got the same error:

```python
    @get(path = "/healthz/{model_name:str}")
    async def model_healthcheck(
        self,
        model_name: str,
        headers: Optional[Headers] = None,
        cookies: Optional[Dict[str, Any]] = None,
    ) -> Response[HealthCheckResponse]:
        """
        Performs a Healthcheck on a model server
        """
        resp = await GatewayEndpoint.forward(
            path = f"{self.path}/",
            model = model_name,
            method = "GET",
            headers = headers,
            cookies = cookies,
        )
        return Response(content=resp)

...
    @get(path = "/healthz/{model_name:str}")
    async def model_healthcheck(
        self,
        model_name: str,
        headers: Optional[Headers] = None,
        cookies: Optional[Dict[str, Any]] = None,
    ) -> HealthCheckResponse:
        """
        Performs a Healthcheck on a model server
        """
        return await GatewayEndpoint.forward(
            path = f"{self.path}/",
            model = model_name,
            method = "GET",
            headers = headers,
            cookies = cookies,
        )

```


```
{
  "error": "500: Unable to serialize response content"
}
```

For sanity check, the `GatewayEndpoint.forward` function is just a wrapper around `httpx.AsyncClient.request` and there are no configured `response_class` for `Starlite` app

**Comment by provinzkraut** [comment] 2022-11-09 09:42
@trisongz Can you provide an MCVE so we can reproduce the behaviour and better help you out? 
Specifically one that includes this part:
> GatewayEndpoint.forward function is just a wrapper around httpx.AsyncClient.request

**Comment by provinzkraut** [comment] 2022-11-09 16:50
Okay, this is helpful. Just for future reference, this isn't really an MVCE. For future, reference, this is the minimal code that can be used to reproduce your issue:

```python
import httpx
from pydantic import BaseModel

from starlite import Response, create_test_client
from starlite.handlers import get


class HealthCheckResponse(BaseModel):
    status: str


@get(path="/healthz")
async def healthcheck() -> Response[HealthCheckResponse]:
    resp = httpx.Response(status_code=200)
    return Response(content=resp)


with create_test_client(route_handlers=[healthcheck]) as client:
    res = client.get("/healthz")
    print(res.json())
```

This also better demonstrates the core of your issue.

What you are doing can't work, take a close look at your data types. You are telling starlite that you are returning a `HealthCheckResponse`, but what you're actually returning is an instance of `httpx.Response`, which is not serializable into a `HealthCheckResponse`. `HealthCheckResponse` represents the **content** of the `httpx.Response`, not the response object itself.

What works is something like this:

```python
import json

import httpx
from pydantic import BaseModel

from starlite import create_test_client
from starlite.handlers import get


class HealthCheckResponse(BaseModel):
    status: str


@get(path="/healthz")
async def healthcheck() -> HealthCheckResponse:
    resp = httpx.Response(status_code=200, content=json.dumps({"status": "OK"}))
    return resp.json()


with create_test_client(route_handlers=[healthcheck]) as client:
    res = client.get("/healthz")
    print(res.json())
```

But you will not get around serializing the response content in some form. Returning the `httpx.Response` directly cannot work, since it's not an ASGI-Callable, and therefore cannot be used as such.

**Comment by provinzkraut** [comment] 2022-11-11 11:14
@trisongz I'm going to close this for now. Feel free to reopen or create a discussion about it should you have more questions!

**Closed by provinzkraut** 2022-11-11 11:14 UTC
