### ISSUE TITLE
url_for and route_reverse aware not aware of their locations for mounted apps

### ISSUE THREAD

**Issue by scott2b** [starlite-api/starlite#788] opened 2022-11-10 16:14 UTC
### Discussed in https://github.com/starlite-api/starlite/discussions/774

When calling, e.g. `url_for` for a route in a mounted application via the request object, the resulting URL is missing the mount prefix. This is also the case for the relative paths returned by route_reverse calls.

**Comment by Goldziher** [comment] 2022-11-10 18:35
Yes, we are only passing the mount path into the mount. This is done by design because the assumption is that the mounted app might have internal routing logic.

You can use the `asgi` decorator without mounting. Will that work for your use case?

**Comment by scott2b** [comment] 2022-11-10 20:15
I'm not really sure. I don't think I know what that means entirely. I am doing something like this:

```
v1_app = Starlite( ....

v1_asgi = asgi(path="/v1", is_mount=True)(v1_app)

app = Starlite(
    route_handlers=[v1_asgi],
)
```

If I set `is_mount` to False everything just kind of breaks. I am not sure where my routes are at that point -- the openapi.json schema is empty of servers and paths and none of my routes defined in v1_app appear to be available.

**Comment by Goldziher** [comment] 2022-11-10 20:26
hmm, you are using is_mount to mount Starlite applications inside Starlite... 😉 , thats not what this was designed for to be honest. Whats the use case there? Why not simply use a router for this instead of mounting?


```python
from starlite import Router, Starlite

v1_router = Router(path="v/1", route_handlers=[...])

app = Starlite(route_handlers=[v1_router])

```

**Comment by scott2b** [comment] 2022-11-10 21:21
Right, the router approach seems simpler, but the docs don't really turn out right for this:

- The various routes from the different routers are interleaved with no conceptual separation. So for a versioning scheme like this I end up with 2 of every route with the same name in the docs with the only distinction being apparent if you inspect the path for the route.
- The schemas are disambiguated to a single instance for each name, making it unclear how I would implement a versioning scheme for schemas other than to give them distinct names.

Ideally, I think I would have 2 separate sets of documentation, but I am not really sure how that would be achieved with a routing scheme vs mounting.

**Comment by peterschutt** [comment] 2022-11-10 22:17
This has come up before: https://github.com/starlite-api/starlite/issues/241#issuecomment-1191976760.

With `Starlite` being a subclass of `Router` it feels like it should be possible to have an openapi config set at the router level that serves the `/schema` path under that route prefix, but I haven't looked into it at any great level of detail.

Perhaps a solution could be tied in with #768, however the want for separating docs at the router level isn't necessarily unique to versioning.

**Comment by Goldziher** [comment] 2022-11-12 09:15
Ok, I am closing this for now - you can open a different issue regarding mounting Starlite apps inside Starlite etc.

**Closed by Goldziher** 2022-11-12 09:15 UTC
