### ISSUE TITLE
Bug: keyerror originating from pydantic `schema()` function

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#596] opened 2022-10-14 14:43 UTC
When creating a plugin for #591 I noticed this:

```python-traceback
Traceback (most recent call last):
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 408, in main
    run(
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/peter/.pyenv/versions/3.10.8/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/peter/.pyenv/versions/3.10.8/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/peter/.pyenv/versions/3.10.8/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/peter/PycharmProjects/starlite-hello-world/./main.py", line 19, in <module>
    app = Starlite(route_handlers=[hello_world], plugins=[TypedDictPlugin()])
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/starlite/app.py", line 360, in __init__
    self.openapi_schema = self.openapi_config.create_openapi_schema_model(self)
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/starlite/config/openapi.py", line 180, in create_openapi_schema_model
    return construct_open_api_with_schema_class(schema)
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/pydantic_openapi_schema/utils/utils.py", line 54, in construct_open_api_with_schema_class
    schema_definitions = schema(schema_classes, ref_prefix=REF_PREFIX)["definitions"]
  File "/home/peter/.cache/pypoetry/virtualenvs/starlite-hello-world-nPMVAxaQ-py3.10/lib/python3.10/site-packages/pydantic/schema.py", line 157, in schema
    model_name = model_name_map[model]
KeyError: <class 'pydantic.main.DataType'>
```
(need to install pydantic with `--no-binary` to get the full traceback).

The issue seems to be coming from two separate pydantic models being generated with the same name, one for the `data` kwarg, and another for the return type.

This was the handler:

```python
class DataType(TypedDict):
    """A typed dict."""

    a: str
    b: int


@post("/")
def hello_world(data: DataType) -> DataType:
    """Route Handler that outputs hello world."""
    return data
```

There is a branch to reproduce this in the hello-world repo: https://github.com/starlite-api/starlite-hello-world/tree/keyerror-demo. In that repo, the file `typeddict_plugin.py` contains:

```python
class TypedDictPlugin(PluginProtocol[dict]):
    """The class for which we create a plugin.

    For example, could be a base ORM class such as "Model" or "Document"
    etc.
    """

    def __init__(self) -> None:
        """_"""
        self._to_pydantic_class_counter = 0

    def to_pydantic_model_class(self, model_class: type[dict], **kwargs: Any) -> type[BaseModel]:
        """Given a model_class, convert it to a subclass of the pydantic
        BaseModel."""
        pydantic_class = create_model(  # type:ignore[call-overload]
            f"{model_class.__name__}_{self._to_pydantic_class_counter}",
            **{k: (v, ...) for k, v in get_type_hints(model_class).items()},
        )
        self._to_pydantic_class_counter += 1
        return pydantic_class  # type:ignore[no-any-return]
```
Notice the logic there to ensure that all generated models have unique names - removing that logic should cause the issue to reproduce.

**Comment by Goldziher** [comment] 2022-10-23 18:28
@peterschutt is this fixed?

**Comment by peterschutt** [comment] 2022-10-24 03:40
I haven't specifically fixed it, I'll try to simplify a repro tonight.

**Comment by Goldziher** [comment] 2022-11-12 09:17
ok, please close this if its not actual

**Comment by peterschutt** [comment] 2022-11-12 09:48
Unless something has changed with pydantic internals, it's actual, but AFK right now so cannot confirm.

The linked branch is still there in the hello world app, the issue coming from the fact that a model is generated for the `data` kwarg, and also for the return annotation. The fact that the two generated models have the same name, an error would raise out of pydantic internals.

The SQLAlchemy plug-in has `self._model_namespace_map` so that a model isn't generated with the same name twice, and that would fix this problem too, but there is no requirement for that in the plug-in protocol or mention of that requirement in the docs about plugins. So maybe this is a documentation issue, or we should internally handle caching of generated pydantic models from plugins.

**Comment by Goldziher** [comment] 2022-12-11 08:21
Ok, this is not a bug. Its simply an error in implementation on your end. You should ensure that the plugin is able to handle the range of data you pass into it. Closing this.

**Closed by Goldziher** 2022-12-11 08:21 UTC
Labels: bug
