### ISSUE TITLE
Bug: middleware not excluding static path

### ISSUE THREAD

**Issue by ravi-b-m** [starlite-api/starlite#1149] opened 2023-02-04 21:43 UTC
I have a auth middleware and I want to exclude static routes defined by static file config and they are not excluded

```python
auth_mw = DefineMiddleware(JWTAuthenticationMiddleware, exclude=["health", "docs"])

app = Starlite(route_handlers=[health_check, InterestsController],
               static_files_config=[
                   StaticFilesConfig(directories=["docs"], path="/docs", name="docs")
               ],
               logging_config=log_config,
               middleware=[auth_mw])
```

How do I exclude static files from middleware ?

**Comment by Goldziher** [comment] 2023-02-05 12:42
can you try:

```python
auth_mw = DefineMiddleware(JWTAuthenticationMiddleware, exclude=["health", "docs.*"])

app = Starlite(route_handlers=[health_check, InterestsController],
     static_files_config=[
         StaticFilesConfig(directories=["docs"], path="/docs", name="docs")
     ],
     logging_config=log_config,
     middleware=[auth_mw])
```

the value is a regex.

**Comment by ravi-b-m** [comment] 2023-02-05 13:29
unfortunately that didn;t work
```python
auth_mw = DefineMiddleware(JWTAuthenticationMiddleware, exclude=["health", "docs.*"])

app = Starlite(route_handlers=[health_check, InterestsController],
               static_files_config=[
                   StaticFilesConfig(directories=["docs"], path="/docs", name="docs")
               ],
               logging_config=log_config,
               middleware=[auth_mw])

if __name__ == "__main__":
    # port = environ.get("CDSW_READONLY_PORT")
    port = 8000
    uvicorn.run("main:app", host="127.0.0.1", port=port, log_level="debug", reload=True)
```
I still 401 ..

**Comment by Goldziher** [comment] 2023-02-05 13:30
> unfortunately that didn;t work
> ```python
> auth_mw = DefineMiddleware(JWTAuthenticationMiddleware, exclude=["health", "docs.*"])
> 
> app = Starlite(route_handlers=[health_check, InterestsController],
>                static_files_config=[
>                    StaticFilesConfig(directories=["docs"], path="/docs", name="docs")
>                ],
>                logging_config=log_config,
>                middleware=[auth_mw])
> 
> if __name__ == "__main__":
>     # port = environ.get("CDSW_READONLY_PORT")
>     port = 8000
>     uvicorn.run("main:app", host="127.0.0.1", port=port, log_level="debug", reload=True)
> ```
> I still 401 ..

Ok, I'll look into it

**Comment by Goldziher** [comment] 2023-02-05 17:19
Hi @ravi-b-m - i can't reproduce this. Please see the following draft PR which shows this is working correctly: https://github.com/starlite-api/starlite/pull/1155

What version of Starlite are you using? can you make sure to be running the latest and try again? i would need a reproduction from you to be able to tackle this further.

**Comment by ravi-b-m** [comment] 2023-02-05 21:55
I am running ` starlite-1.51.0 ` .. still does not work for me.. I will try to create a test app and share -- Thank you for looking into this

**Comment by peterschutt** [comment] 2023-02-05 22:26
Hi @ravi-b-m - an MVCE will be necessary to progress this bug report. If you are looking for a good starting point for that, check out https://github.com/starlite-api/starlite-hello-world.

**Comment by Goldziher** [comment] 2023-02-09 11:21
Ok, closing this for now. @ravi-b-m - if you are able to create a reproduction, feel free to reopen.

**Closed by Goldziher** 2023-02-09 11:21 UTC
Labels: bug, invalid, wontfix
