### ISSUE TITLE
Bug: Validation fails when dataclass model uses slots

### ISSUE THREAD

**Issue by infohash** [starlite-api/starlite#359] opened 2022-08-12 20:01 UTC
`slots` is added in `dataclass` in python 3.10.

```python
from starlite import post
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class User:
    username: str
    group: str

@post(path="/user")
async def create_user(data: User) -> User:
    return data
```

## Request
```json
{
    "username": "starlite",
    "group": "admin"
}
```

## Observed Response
```json
{
    "detail": "Validation failed for POST http://127.0.0.1:8000/user",
    "extra": [
	{
		"loc": [
			"data",
			"username"
		],
		"msg": "field required",
		"type": "value_error.missing"
	},
	{
		"loc": [
			"data",
			"group"
		],
		"msg": "field required",
		"type": "value_error.missing"
	}
],
    "status_code": 400
}
```

## Expected Response
```json
{
    "username": "starlite",
    "group": "admin"
}
```

## What's working
Pydantic model is working.

```python
from pydantic import BaseModel


class User(BaseModel):
    username: str
    group: str
```

**Comment by Goldziher** [comment] 2022-08-13 13:50
After testing this out - the issue is 100% in pydantic. I updated an issue there that is now linked above. 

Closing this one since we cant (read shouldnt) do anything about it in Starlite.

**Closed by Goldziher** 2022-08-13 13:50 UTC
Labels: bug
