### ISSUE TITLE
Inherited Pydantic's GenericModel or dataclasses as dependencies

### ISSUE THREAD

**Issue by vrslev** [starlite-api/starlite#138] opened 2022-06-11 14:58 UTC
Dependency that outputs instance of a class that inherits from a class that inherits from `pydantic.generics.GenericModel` or `dataclasses.dataclass` (I know 😃) are reverted back to their base classes.

```python
from typing import Generic, Optional, TypeVar, cast

from pydantic import BaseModel
from pydantic.generics import GenericModel
from starlite import Provide, Starlite, get

T = TypeVar("T")


class Store(GenericModel, Generic[T]):
    """Abstract store"""

    model: type[T]

    def get(self, id: str) -> Optional[T]:
        raise NotImplementedError


class DictStore(Store[T]):
    """In-memory store implementation"""

    def get(self, id: str) -> Optional[T]:
        return None


class Item(BaseModel):
    name: str


@get()
def root(store: Store[Item]) -> Optional[Item]:
    # Expected DictStore[Item], got Store[Item].
    # That's why the line below will fail.
    assert type(store) is DictStore
    return cast(DictStore[Item], store).get("0")  # Unreachable


def get_item_store() -> Store[Item]:
    return DictStore(model=Item)


deps = {"store": Provide(get_item_store, use_cache=True)}
app = Starlite(route_handlers=[root], debug=True, dependencies=deps)

```

As you can see, there are `Store` class that inherits from `GenericModel` and `DictStore` that implements `Store`. We set up dependencies in such a way that `store` argument corresponds with `DictStore`. We expect `DictStore` to be injected in route handler but it fails because Pydantic (right?) tries to give the most appropriate type for what we asked for.

I'm not sure if this is a Starlite issue. Also I don't think dependencies should be validated—so strictly or at all.

**Comment by Goldziher** [comment] 2022-06-11 16:06
Hmm. Interesting. You're Welcome to add a PR. Otherwise, can you add a failing test?

 @peterschutt and myself will take a look.

**Comment by vrslev** [comment] 2022-06-11 16:08
@Goldziher I'm not sure where to begin with a PR. Can you point out the place in code dependency resolution coupled with Pydantic parsing lives?

**Comment by Goldziher** [comment] 2022-06-11 18:13
Lemme take a look - always a good starting point is a failing test, so ill see about that.

**Comment by Goldziher** [comment] 2022-06-11 18:28
Ok, I see the issue - hmm, will work on a fix now.

**Comment by Goldziher** [comment] 2022-06-11 18:48
Ok, so the issue is this: we use the type annotations to determine what kind of value should be injected. In this case, its the return value of the `get_item_store` function, which is typed as returning `Store[Item]`. We have to do this because we are pre-computing the requirements during application bootstrap, which ensures this is performant - otherwise we will need to dynamically compute and that will be quite bad. 

Anyhow, this logic [can be found here](https://github.com/starlite-api/starlite/blob/main/starlite/signature.py#L61) if you want to take a look. 

There is no way to "fix" the above code, because it uses inheritence. The way I resolved the issue is by re-writing the example you gave me in a test:

```python
from typing import Generic, Optional, TypeVar, cast, Type

from pydantic import BaseModel
from pydantic.generics import GenericModel
from starlette.status import HTTP_200_OK

from starlite import Provide, Starlite, get, create_test_client

T = TypeVar("T")


class Store(GenericModel, Generic[T]):
    """Abstract store"""

    model: Type[T]

    def get(self, id: str) -> Optional[T]:
        raise NotImplementedError


class Item(BaseModel):
    name: str

class DictStore(Store[Item]):
    """In-memory store implementation"""

    def get(self, id: str) -> Optional[T]:
        return None


@get("/")
def root(store: DictStore) -> Optional[Item]:
    assert isinstance(store, DictStore)
    return store.get("0")


def get_item_store() -> DictStore:
    return DictStore(model=Item)


def test_store_injection():
    with create_test_client(
            root,
            dependencies={"store": Provide(get_item_store, use_cache=True)}
    ) as client:
        response = client.get("/")
        assert response.status_code == HTTP_200_OK
```

This works. I know it doesn't offer the kind of flexiblity you'd like, with being able to define different types of `DictStores`, but this is the best that I could come up with in a reasonable time. 

Hope it helps. And of course you're welcome to submit a PR if you have a better solution in mind.

**Comment by peterschutt** [comment] 2022-06-11 22:59
> Also I don't think dependencies should be validated—so strictly or at all.

This is worth discussing.

I'm spending a bit of time to understand this area of the code more completely before I commit to an opinion, but maybe it is feasible that we 'trust' the developer in cases where we know the parameter to the handler function is a dependency and just send `Any` to `create_model()` so pydantic passes the result straight through. Or we have a "trust-me" mode `store: Store[Item] = Dependency(trust_me_ok=True)`. I'd probably choose the opt-in version if this turned out to be feasible.

**Comment by peterschutt** [comment] 2022-06-12 00:35
>  it fails because Pydantic (right?)

Pydantic does behave differently if there are generics involved. Take modified test with all the generic stuff stripped out which passes:

```python
class Store:  # (GenericModel, Generic[T]):
    """Abstract store"""

    model: Type[T]

    def get(self, id: str) -> Optional[T]:
        raise NotImplementedError


class Item(BaseModel):
    name: str


class DictStore(Store):  # [T], Generic[T]):
    """In-memory store implementation"""

    def get(self, id: str) -> Optional[T]:
        return None


@get("/")
def root(store: Store) -> Optional[Item]:
    assert isinstance(store, DictStore)
    return store.get("0")


def get_item_store() -> DictStore:
    instance = DictStore()
    return instance


def test_generic_model_injection() -> None:
    with create_test_client(root, dependencies={"store": Provide(get_item_store, use_cache=True)}) as client:
        response = client.get("/")
        assert response.status_code == HTTP_200_OK
```

So pretty confident we'd have to take the behavior of pydantic as a given. The way I see it that leaves:
- document the issue and leave it
- try to do some tomfoolery in `SignatureModel.parse_values_from_connection_kwargs()` where we compare the value provided for the dependency against the one that is generated from it by the `SignatureModel` for the parameter key and if they share a common base class, overwrite the output value to be the one direct from the dependency.
- somehow signal to `SignatureModel.parse_values_from_connection_kwargs()` that in some cases we don't even want to use the signature model to parse/validate a value provided for a dependency. This issue is case in point.
- have `model_function_signature()` create a type for a known dependency function parameter that doesn't  make pydantic resolve it to the broader type. Would behave similar to above, but we'd be broadening the type of the field on the parameter model and still passing the dependency value through it rather than bypassing. This is similar to the "trust-me" mode I mentioned in my previous comment.

**Comment by Goldziher** [comment] 2022-06-12 05:53
> >  it fails because Pydantic (right?)
> 
> Pydantic does behave differently if there are generics involved. Take modified test with all the generic stuff stripped out which passes:
> 
> ```python
> class Store:  # (GenericModel, Generic[T]):
>     """Abstract store"""
> 
>     model: Type[T]
> 
>     def get(self, id: str) -> Optional[T]:
>         raise NotImplementedError
> 
> 
> class Item(BaseModel):
>     name: str
> 
> 
> class DictStore(Store):  # [T], Generic[T]):
>     """In-memory store implementation"""
> 
>     def get(self, id: str) -> Optional[T]:
>         return None
> 
> 
> @get("/")
> def root(store: Store) -> Optional[Item]:
>     assert isinstance(store, DictStore)
>     return store.get("0")
> 
> 
> def get_item_store() -> DictStore:
>     instance = DictStore()
>     return instance
> 
> 
> def test_generic_model_injection() -> None:
>     with create_test_client(root, dependencies={"store": Provide(get_item_store, use_cache=True)}) as client:
>         response = client.get("/")
>         assert response.status_code == HTTP_200_OK
> ```
> 
> So pretty confident we'd have to take the behavior of pydantic as a given. The way I see it that leaves:
> - document the issue and leave it
> - try to do some tomfoolery in `SignatureModel.parse_values_from_connection_kwargs()` where we compare the value provided for the dependency against the one that is generated from it by the `SignatureModel` for the parameter key and if they share a common base class, overwrite the output value to be the one direct from the dependency.
> - somehow signal to `SignatureModel.parse_values_from_connection_kwargs()` that in some cases we don't even want to use the signature model to parse/validate a value provided for a dependency. This issue is case in point.
> - have `model_function_signature()` create a type for a known dependency function parameter that doesn't  make pydantic resolve it to the broader type. Would behave similar to above, but we'd be broadening the type of the field on the parameter model and still passing the dependency value through it rather than bypassing. This is similar to the "trust-me" mode I mentioned in my previous comment.
> 
> I think we should at least consider the latter 3 options (and any others I've missed) before we allow to settle for the first.

I don't think this is feasible. Let's leave this issue open for now and revisit it once you're more familiar with the pertinent code.

**Comment by vrslev** [comment] 2022-06-13 08:00
@Goldziher
Obviously we shouldn’t add any code that breaks abstractions just to support Pydantic generics.
What do you think about removing dependency validation?

**Comment by Goldziher** [comment] 2022-06-13 08:27
> @Goldziher Obviously we shouldn’t add any code that breaks abstractions just to support Pydantic generics. What do you think about removing dependency validation?

I would rather have validation than not, so strictly removing is not in the books IMO. What's possible is to consider making this optional or configurable. If we can do the following:

1. ensure there is a simple and intuitive API for configuration validation
2. ensure that the dependency resolution and injection is not negatively affect by this change
3. preserve existing functionalities

This would be a great addition I think.

**Comment by vrslev** [comment] 2022-06-15 06:39
I like that Starlite validates dependencies! And I don't know the code base good enough to make this bold changes.

My main use case was to use `dataclasses` with `typing.Protocol`. I ended up with the solution where base class `Store` is not a `dataclass` so Pydantic can't convert `DictStore` to `Store`.

```python
class Store(Protocol[T]):
    """Abstract store"""

    model: type[T]

    def get(self, id: str) -> Optional[T]:
        raise NotImplementedError


@dataclass
class DictStore(Store[T]):
    """In-memory store implementation"""

    model: type[T]

    def get(self, id: str) -> Optional[T]:
        return None
```

**Comment by peterschutt** [comment] 2022-06-15 07:30
I think validation of dependencies is ultimately a good thing, but I reckon it needs more thought.

Take this test:

```python
def test_dependency_invalid() -> None:

    class C(Controller):
        path = ""
        dependencies = {"value": Provide(lambda: "one-three")}

        @get()
        def test(self, value: float) -> Dict[str, float]:
            return {"value": value}

    with create_test_client(route_handlers=[C]) as client:
        resp = client.get("/")

    assert resp.status_code != 400
```

In this case, we resolve that `value` is a dependency yet still return a 400 when the validation fails yet the client has no way to control that validated value. The response should be 5XX.

So yeah, it is neat to have validation on dependencies, but the paradigm isn't "right" at the moment.

**Comment by Goldziher** [comment] 2022-06-15 08:04
Fair points

**Comment by Goldziher** [comment] 2022-06-15 19:29
So what's actionable here?

1. status for dependency validation should be changed to 500. 

Anything else?

**Comment by peterschutt** [comment] 2022-06-15 23:22
Here's what I'd like to have resolved:

1. do we want to give developers a way to avoid pydantic validation of their dependency altogether (I've put this as 1. as I want to ensure that I haven't hijacked the primary issue here).
2. status for dependency validation should be changed to 500.
3. order of priority when there is both a client side and dependency validation error, e.g., raise in order of status code ascending/descending, or some other rule.

On point 1. I think generics are a tricky space for pydantic to operate within, and there will always be edge cases, or they will take an opinion about resolving generic types that will not be desirable to every case, such as the case in this issue. The most recent open issue in the pydantic tracker is relatable: https://github.com/samuelcolvin/pydantic/issues/4161.

We are in a shared, but separate space to pydantic on that front. We use pydantic under the hood to resolve/validate these types, but that's not immediately obvious (https://starlite-api.github.io/starlite/usage/2-route-handlers/0_route_handlers_concept/#). When developers are injecting dependencies into Starlite handlers, it is not necessarily going to be front-of-mind that they are going to be receiving their dependency _after_ it has worked its way through the pydantic internals, and so it is possible that this type of issue is a consistent theme for us.

**Comment by Goldziher** [comment] 2022-06-28 19:21
@peterschutt - can you spin out followup issues out of this, and then close this one?

**Comment by peterschutt** [comment] 2022-06-28 23:26
OK, that's done, I'll close this but feel free to reopen @vrslev if you don't think original issue captured in one of the spin-offs.

**Closed by peterschutt** 2022-06-28 23:26 UTC
Labels: bug
