### ISSUE TITLE
Bug: Cache-enabled endpoints raise PicklingError when type_encoders is specified in Starlite config.

### ISSUE THREAD

**Issue by rhizome-labs** [starlite-api/starlite#1096] opened 2023-01-25 02:48 UTC
**Describe the bug**

I have a basic cached endpoint like this:

```
@get(
        path="/",
        cache=30,
        include_in_schema=False,
    )
    async def get_stuff(self) -> dict:
        return {"data": "test!"}
```

In my Starlite config I have some type encoders set up for Beanie compatability.

```
# Set up Beanie encoders.
beanie_encoders = {
    PydanticObjectId: str,
}

app = Starlite(
    cache_config=cache_config,
    debug=False if ENVIRONMENT == "production" else True,
    route_handlers=[...],
    on_startup=[app_init],
    type_encoders=beanie_encoders,
)
```

When visiting the / endpoint, I get a PicklingError that reads:

```
PicklingError on GET /api/v1/collections/machin/prime
Can't pickle <function <lambda> at 0x1107e5800>: attribute lookup <lambda> on starlite.utils.serialization failed
```

![CleanShot 2023-01-25 at 11 48 00@2x](https://user-images.githubusercontent.com/53635700/214469461-da03a374-0855-4c16-bb02-6249315599ec.jpg)

**To Reproduce**
1. Create an endpoint with `cache` param.
2. Set up Redis cache config from Starlite docs.
3. Set up type_encoders shown above.
4. Visit the cached endpoint.

**Comment by provinzkraut** [comment] 2023-01-25 10:33
Confirmed. 

MCVE:

```python
from starlite import CacheConfig, Starlite, TestClient, get
from starlite.cache import SimpleCacheBackend


@get(cache=30)
def cached() -> list[str]:
    return ["hello"]


app = Starlite(
    [cached],
    type_encoders={int: str},
    cache_config=CacheConfig(backend=SimpleCacheBackend()),
    debug=True
)

with TestClient(app=app) as client:
    assert client.get("/").status_code == 200
```

So, this is a tricky one. We allow setting `type_encoders` on the `Response` class for convenience when subclassing `Response`. This is then also used internally to construct ad-hoc `type_encoders` maps from partial maps as passed to the `type_encoders` params on the application layers. I can see two possible (straightforward) solutions to this, each with their own downsides:

1. "It's not a bug":  We document this constraint on `type_encoders` that they must be picklable when used together with a cache. This would mean that you can't use lambdas in `type_encoders`, which can make them unnecessarily verbose
2. We copy the response before it's pickled. After the response has been rendered, `type_encoders` won't be touched again. We could construct a new response instance, with the rendered body as its content, and cache this instance instead of the original response. The downside of this would be that it could possibly be a lossy process if a custom response class is used that violates LSP, or has middleware that depends on some instance attribute being set via additional parameters in a custom `__init__` method. I'd say both are edge cases, and the latter one is also bad practice, so it might be okay to dismiss those 

@starlite-api/maintainers I'd like to get second opinions on this before moving forward.

**Comment by Goldziher** [comment] 2023-01-25 15:19
> Confirmed. 
> 
> MCVE:
> 
> ```python
> from starlite import CacheConfig, Starlite, TestClient, get
> from starlite.cache import SimpleCacheBackend
> 
> 
> @get(cache=30)
> def cached() -> list[str]:
>     return ["hello"]
> 
> 
> app = Starlite(
>     [cached],
>     type_encoders={int: str},
>     cache_config=CacheConfig(backend=SimpleCacheBackend()),
>     debug=True
> )
> 
> with TestClient(app=app) as client:
>     assert client.get("/").status_code == 200
> ```
> 
> So, this is a tricky one. We allow setting `type_encoders` on the `Response` class for convenience when subclassing `Response`. This is then also used internally to construct ad-hoc `type_encoders` maps from partial maps as passed to the `type_encoders` params on the application layers. I can see two possible (straightforward) solutions to this, each with their own downsides:
> 
> 1. "It's not a bug":  We document this constraint on `type_encoders` that they must be picklable when used together with a cache. This would mean that you can't use lambdas in `type_encoders`, which can make them unnecessarily verbose
> 2. We copy the response before it's pickled. After the response has been rendered, `type_encoders` won't be touched again. We then construct a new response instance, with the rendered body as its content, and cache this instance instead of the original response. The downside of this would be that it could possibly be a lossy process if a custom response class is used that violates LSP, or has middleware that depends on some instance attribute being set via additional parameters in a custom `__init__` method. I'd say both are edge cases, and the latter one is also bad practice, so it might be okay to dismiss those 
> 
> @starlite-api/maintainers I'd like to get second opinions on this before moving forward.

Well, I'd go for option one and make it clear that when enabling cache with type encoders they should be pickable - otherwise it's not required. I would then add validation for this combination to through an informative ImproperlyConfiguredException.

**Comment by peterschutt** [comment] 2023-01-26 00:12
I'd go with option 1 also.

**Comment by provinzkraut** [comment] 2023-01-26 08:22
> I would then add validation for this combination

How would we validate that though? Try to pickle `type_endoders`? It’s also not the only thing that could cause issues with the pickling. If we’re to add validation here, I’d say we do it for the general case of using caching, not just this specific one.

**Comment by Goldziher** [comment] 2023-01-26 09:55
> > I would then add validation for this combination
> 
> How would we validate that though? Try to pickle `type_endoders`? It’s also not the only thing that could cause issues with the pickling. If we’re to add validation here, I’d say we do it for the general case of using caching, not just this specific one.

Encoders you can validate at startup. The actual content you cannot - it's runtime.

**Comment by provinzkraut** [comment] 2023-01-26 10:08
> Encoders you can validate at startup. The actual content you cannot - it's runtime.

That's not what I meant. What I meant was that afaik the only thing we could do is try to pickle, and tell the user that it's not picklable if that fails. But we'd be hand-picking a very particular case that we test for here. There are many things someone could do with a custom response that makes it not picklable, and it feels wrong to me to only validate this one particular case. That's why I think *if* we're adding this validation, we should add general validation for the "pickleability" when enabling caching.

**Comment by Goldziher** [comment] 2023-01-26 13:49
> > Encoders you can validate at startup. The actual content you cannot - it's runtime.
> 
> That's not what I meant. What I meant was that afaik the only thing we could do is try to pickle, and tell the user that it's not picklable if that fails. But we'd be hand-picking a very particular case that we test for here. There are many things someone could do with a custom response that makes it not picklable, and it feels wrong to me to only validate this one particular case. That's why I think _if_ we're adding this validation, we should add general validation for the "pickleability" when enabling caching.

I understood you the first time 😉 , my point is this:

1. you can try to pickle the encoders when the route handler is initialized - this is validation at the startup. This is what I regard as validation, since it checks the configuration / setup and is happening before the app is fully running.
2. you can handle pickle errors by re-raising an informative error if the response cannot be pickled - this is runtime, and its not validation, but is rather a way to communicate to the user in a more informative way. 

You can of course do both - and its probably a good idea to do both. I would not though handle both as the same case, because they are not- as the query you raised pointed out.

**Comment by provinzkraut** [comment] 2023-01-26 14:03
> > > Encoders you can validate at startup. The actual content you cannot - it's runtime.
> > 
> > 
> > That's not what I meant. What I meant was that afaik the only thing we could do is try to pickle, and tell the user that it's not picklable if that fails. But we'd be hand-picking a very particular case that we test for here. There are many things someone could do with a custom response that makes it not picklable, and it feels wrong to me to only validate this one particular case. That's why I think _if_ we're adding this validation, we should add general validation for the "pickleability" when enabling caching.
> 
> I understood you the first time wink , my point is this:
> 
>     1. you can try to pickle the encoders when the route handler is initialized - this is validation at the startup. This is what I regard as validation, since it checks the configuration / setup and is happening before the app is fully running.
> 
>     2. you can handle pickle errors by re-raising an informative error if the response cannot be pickled - this is runtime, and its not validation, but is rather a way to communicate to the user in a more informative way.
> 
> 
> You can of course do both - and its probably a good idea to do both. I would not though handle both as the same case, because they are not- as the query you raised pointed out.

And I understood you as well. It seems like we are talking about different things here. 

1. My point is that there can be things besides using unpicklable objects in `type_encoders` that can prevent a response from being pickled. Some of them can be checked during startup, like `type_encoders`. I'm saying that I think *if we do such a validation*, it should include more than just checking `type_encoders`
2. I'm not talking about runtime validation when I said all we can do is try to pickle and wrap a potential `PickleError`. During startup or runtime, pickling something is the only way to tell if it can be pickled, as there is no `can_be_pickled` function in the standard library.

**Comment by Goldziher** [comment] 2023-01-26 14:17
We have no argument here @provinzkraut - validate away

**Comment by provinzkraut** [comment] 2023-01-26 15:52
@rhizome-labs This should be fixed in the next Starlite release, or if you're using Starlite from `main`.

I also created #1104 for the validation + documentation.

**Closed** 2023-01-27 10:02 UTC
Labels: bug
